version: '3.8'
services:
  reverseproxy:
    build: ../nginx
    container_name: nginx
    networks:
      - app-network
    restart: always
    ports:
      - "80:80"
      - "1000:1000"
      - "2001:2001"
    depends_on:
      - consul
      - onboarding
    volumes:
      - ../logs:/var/log/nginx

  consul:
    build:
      context: ../consul
      dockerfile: Dockerfile
    container_name: consul
    networks:
      - app-network
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -config-file=/consul/config/config.json

  onboarding:
    restart: always
    build:
      context: ../onboarding-service
      dockerfile: Dockerfile
    container_name: onboarding-service
    networks:
        - app-network
    environment:
      - HOST_IP=192.168.29.60
      - CONSUL_PORT=1000
      - SERVICE_PORT=2001
    volumes:
      - ../logs:/usr/src/app/logs

  # frontend:
  #   build: ../s-ui
  #   container_name: frontend
  #   networks:
  #     - app-network
  #   restart: always
  #   ports:
  #     - "4200:80"
  #   depends_on:
  #     - reverseproxy
  
networks:
  app-network:
    driver: bridge